name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI tests on Chrome and Firefox
        run: |
          cd task_3_ui_tests
          pytest --browser=chrome,firefox --html=report.html --self-contained-html

      - name: Add report to artifact
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-artifacts
          path: |
            task_3_ui_tests/report.html
            task_3_ui_tests/screenshots